---
- name: Run container
  gather_facts: no
  hosts: catbox
  become: true
  become_method: sudo
  tasks:
    - name: restart container
      community.docker.docker_compose_v2:
        docker_cli: /usr/bin/docker
        project_src: /opt/compose
        files:
        - compose.yml
        state: restarted
